[build]
  command = "echo REACT_APP_SUPABASE_URL=$REACT_APP_SUPABASE_URL && echo REACT_APP_SUPABASE_KEY=$REACT_APP_SUPABASE_KEY && npm run build"
  publish = "build"

[build.environment]
  REACT_APP_SUPABASE_URL = "${REACT_APP_SUPABASE_URL}"
  REACT_APP_SUPABASE_KEY = "${REACT_APP_SUPABASE_KEY}"
  REACT_APP_GITHUB_TOKEN = "${REACT_APP_GITHUB_TOKEN}"
  REACT_APP_GPT_KEY = "${REACT_APP_GPT_KEY}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
